name: Blues CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  #  gitleaks:
  #    name: GitLeaks
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #        with:
  #          fetch-depth: 0
  #
  #      - name: Run GitLeaks
  #        uses: gitleaks/gitleaks-action@v2
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build:
    name: Build and Test Blues App
    runs-on: macos-latest
    #    needs: gitleaks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android AAB
        run: flutter build appbundle --release

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages

      - name: Notify Discord Success
        if: success()
        env:
          PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          PAYLOAD=$(jq -n \
            --arg color "1469988" \
            --arg url "$PAGES_URL" \
            --arg desc "Commit: $COMMIT_MESSAGE\nMise à jour du GitHub Page" \
            --arg title "**Frontend update réussie**" \
            --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --arg footer_icon "https://www.snsm.org/themes/custom/customer/images/logo.png" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "url": $url,
                  "description": $desc,
                  "color": ($color|tonumber),
                  "timestamp": $timestamp,
                  "footer": {
                    "icon_url": $footer_icon,
                    "text": "Deployment Bot"
                  }
                }
              ]
            }')
          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK }}

      # Notify Failure
      - name: Notify Discord Failure
        if: failure()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          FAILED_STEP=$(jq -r '.steps[] | select(.conclusion=="failure") | .name' $GITHUB_STEP_SUMMARY || echo "Unknown step")
          PAYLOAD=$(jq -n \
            --arg color "6485270" \
            --arg url "$JOB_URL" \
            --arg desc "Commit: $COMMIT_MESSAGE\nFailed at $FAILED_STEP" \
            --arg title "**Frontend update échouée**" \
            --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --arg footer_icon "https://www.snsm.org/themes/custom/customer/images/logo.png" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "url": $url,
                  "description": $desc,
                  "color": ($color|tonumber),
                  "timestamp": $timestamp,
                  "footer": {
                    "icon_url": $footer_icon,
                    "text": "Deployment Bot"
                  }
                }
              ]
            }')
          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK }}
